name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      
      - name: Build site
        run: npm run build

      - name: Build tailwindcss
        run: npx tailwindcss -o build/static/index.css --minify

      - name: Setup github user & email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
      
      - name: Commit build
        run: |
          git --work-tree build add --all
          git commit -m "Automatic Build and Deploy run by GitHub Actions"
      
      - name: Push build
        run: git push origin HEAD:gh-pages --force
      